#!/bin/bash
# ============================================================
# Local Claude Code Setup — Qwen3.5-122B on MLX
# ============================================================
# Apple Silicon Mac (64GB+ RAM) で Qwen3.5-122B-A10B-4bit を
# MLX で動かし、Claude Code のtool_use含め完全互換で使えるようにする。
#
# 使い方:
#   ssh user@mac "bash -s" < setup_local_claude.sh
#   または Mac 上で直接:
#   bash setup_local_claude.sh
#
# セットアップ後:
#   ~/ai.sh start   → MLX + プロキシ起動
#   ~/ai.sh stop    → 停止
#   cld              → ローカルAIでClaude Code起動
#   clc              → 本家AnthropicでClaude Code起動
# ============================================================

set -e

MLX_PORT=5000
PROXY_PORT=4001
VENV="$HOME/mlx_env"

# ── Auto-detect RAM and select optimal models ──
RAM_BYTES=$(sysctl -n hw.memsize 2>/dev/null || echo 0)
RAM_GB=$((RAM_BYTES / 1073741824))

if [ "$RAM_GB" -lt 16 ]; then
  echo "ERROR: At least 16GB RAM required. You have ${RAM_GB}GB."
  echo "LOCAL AI needs Apple Silicon Mac with 16GB+ unified memory."
  exit 1
elif [ "$RAM_GB" -le 18 ]; then
  # 16GB: smallest model only
  MODEL_MAIN="mlx-community/Qwen3.5-4B-4bit"
  MODEL_FAST=""
  MODEL_VISION=""
  TIER="16GB (Minimal)"
elif [ "$RAM_GB" -le 24 ]; then
  # 24GB: 9B main
  MODEL_MAIN="mlx-community/Qwen3.5-9B-4bit"
  MODEL_FAST=""
  MODEL_VISION="mlx-community/Qwen3-VL-4B-Instruct-4bit"
  TIER="24GB (Standard)"
elif [ "$RAM_GB" -le 36 ]; then
  # 32GB: 35B MoE (active 3B, very fast)
  MODEL_MAIN="mlx-community/Qwen3.5-35B-A3B-4bit"
  MODEL_FAST=""
  MODEL_VISION="mlx-community/Qwen3-VL-4B-Instruct-4bit"
  TIER="32GB (Pro)"
elif [ "$RAM_GB" -le 64 ]; then
  # 48-64GB: 35B main + 9B fast
  MODEL_MAIN="mlx-community/Qwen3.5-35B-A3B-4bit"
  MODEL_FAST="mlx-community/Qwen3.5-9B-4bit"
  MODEL_VISION="mlx-community/Qwen3-VL-8B-Instruct-4bit"
  TIER="64GB (Advanced)"
elif [ "$RAM_GB" -le 96 ]; then
  # 96GB: 122B main + 35B fast
  MODEL_MAIN="mlx-community/Qwen3.5-122B-A10B-4bit"
  MODEL_FAST=""
  MODEL_VISION="mlx-community/Qwen3-VL-8B-Instruct-4bit"
  TIER="96GB (Expert)"
else
  # 128GB+: full fleet
  MODEL_MAIN="mlx-community/Qwen3.5-122B-A10B-4bit"
  MODEL_FAST="mlx-community/Qwen3.5-35B-A3B-4bit"
  MODEL_VISION="mlx-community/Qwen3-VL-8B-Instruct-4bit"
  TIER="128GB (Ultimate)"
fi

# Allow override
MODEL_MAIN="${MLX_MODEL_MAIN:-$MODEL_MAIN}"
MODEL_FAST="${MLX_MODEL_FAST:-$MODEL_FAST}"

echo "========================================"
echo " Local Claude Code Setup"
echo " RAM: ${RAM_GB}GB — Tier: $TIER"
echo " Main:   $MODEL_MAIN"
[ -n "$MODEL_FAST" ] && echo " Fast:   $MODEL_FAST"
[ -n "$MODEL_VISION" ] && echo " Vision: $MODEL_VISION"
echo "========================================"

# -------------------------------------------------------
# 1. Homebrew + Python 3.11
# -------------------------------------------------------
echo "[1/6] Checking Homebrew & Python..."
export PATH="/opt/homebrew/bin:$PATH"

if ! command -v brew &>/dev/null; then
  echo "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! brew list python@3.11 &>/dev/null; then
  echo "Installing Python 3.11..."
  brew install python@3.11
fi

# -------------------------------------------------------
# 2. venv + MLX + aiohttp
# -------------------------------------------------------
echo "[2/6] Setting up Python venv & dependencies..."
if [ ! -d "$VENV" ]; then
  python3.11 -m venv "$VENV"
fi

source "$VENV/bin/activate"
pip install --upgrade pip -q
pip install mlx-lm aiohttp -q
echo "  mlx-lm $(pip show mlx-lm 2>/dev/null | grep Version | cut -d' ' -f2)"

# -------------------------------------------------------
# 3. Download model (if not cached)
# -------------------------------------------------------
echo "[3/6] Downloading models..."
for m in $MODEL_MAIN $MODEL_FAST $MODEL_VISION; do
  [ -z "$m" ] && continue
  if python3 -c "
from huggingface_hub import scan_cache_dir
repos = [i.repo_id for i in scan_cache_dir().repos]
exit(0 if '$m' in repos else 1)
" 2>/dev/null; then
    echo "  $m — cached"
  else
    echo "  $m — downloading..."
    python3 -c "from huggingface_hub import snapshot_download; snapshot_download('$m')"
  fi
done

# -------------------------------------------------------
# 4. Anthropic proxy (with tool_use support)
# -------------------------------------------------------
echo "[4/6] Writing Anthropic proxy..."
base64 -d << 'B64EOF' > "$HOME/anthropic_proxy.py"
IiIiQW50aHJvcGljIE1lc3NhZ2VzIEFQSSAtPiBPcGVuQUkgQ2hhdCBDb21wbGV0aW9ucyBwcm94eSBmb3IgTUxYClN1cHBvcnRzOiB0ZXh0LCBzdHJlYW1pbmcsIHRvb2xfdXNlL3Rvb2xfcmVzdWx0LCBtdWx0aS1tb2RlbCByb3V0aW5nIiIiCmltcG9ydCBqc29uLCB1dWlkLCB0aW1lLCBvcwpmcm9tIGFpb2h0dHAgaW1wb3J0IHdlYiwgQ2xpZW50U2Vzc2lvbgoKIyDilIDilIAgTXVsdGktbW9kZWwgY29uZmlndXJhdGlvbiDilIDilIAKIyBFYWNoIE1MWCBzZXJ2ZXIgcnVucyBvbiBpdHMgb3duIHBvcnQuIFRoZSBwcm94eSByb3V0ZXMgYmFzZWQgb24gdGhlCiMgQW50aHJvcGljIG1vZGVsIG5hbWUgdGhhdCBDbGF1ZGUgQ29kZSBzZW5kcy4KIwojIEFkZCBtb2RlbHMgYnk6CiMgICAxLiBBZGRpbmcgYW4gZW50cnkgdG8gTU9ERUxTIGJlbG93CiMgICAyLiBTdGFydGluZyBhbiBNTFggc2VydmVyIG9uIHRoZSBzcGVjaWZpZWQgcG9ydAojICAgMy4gKE9wdGlvbmFsKSBtYXAgYWRkaXRpb25hbCBBbnRocm9waWMgbmFtZXMgaW4gTU9ERUxfUk9VVEVTCgpNT0RFTFMgPSB7CiAgICAibWFpbiI6IHsKICAgICAgICAibWx4X21vZGVsIjogb3MuZW52aXJvbi5nZXQoIk1MWF9NT0RFTF9NQUlOIiwgIm1seC1jb21tdW5pdHkvUXdlbjMuNS0xMjJCLUExMEItNGJpdCIpLAogICAgICAgICJwb3J0IjogaW50KG9zLmVudmlyb24uZ2V0KCJNTFhfUE9SVF9NQUlOIiwgIjUwMDAiKSksCiAgICAgICAgImxhYmVsIjogIlF3ZW4zLjUtMTIyQiAoZ2VuZXJhbCkiLAogICAgfSwKICAgICJmYXN0IjogewogICAgICAgICJtbHhfbW9kZWwiOiBvcy5lbnZpcm9uLmdldCgiTUxYX01PREVMX0ZBU1QiLCAibWx4LWNvbW11bml0eS9Rd2VuMy41LTM1Qi1BM0ItNGJpdCIpLAogICAgICAgICJwb3J0IjogaW50KG9zLmVudmlyb24uZ2V0KCJNTFhfUE9SVF9GQVNUIiwgIjUwMDEiKSksCiAgICAgICAgImxhYmVsIjogIlF3ZW4zLjUtMzVCLUEzQiAoZmFzdCkiLAogICAgfSwKICAgICJ2aXNpb24iOiB7CiAgICAgICAgIm1seF9tb2RlbCI6IG9zLmVudmlyb24uZ2V0KCJNTFhfTU9ERUxfVklTSU9OIiwgIm1seC1jb21tdW5pdHkvUXdlbjMtVkwtOEItSW5zdHJ1Y3QtNGJpdCIpLAogICAgICAgICJwb3J0IjogaW50KG9zLmVudmlyb24uZ2V0KCJNTFhfUE9SVF9WSVNJT04iLCAiNTAwMiIpKSwKICAgICAgICAibGFiZWwiOiAiUXdlbjMtVkwtOEIgKHZpc2lvbikiLAogICAgfSwKfQoKIyBNYXAgQW50aHJvcGljIG1vZGVsIG5hbWVzIC0+IHdoaWNoIGJhY2tlbmQgdG8gdXNlCk1PREVMX1JPVVRFUyA9IHsKICAgICMgU29ubmV0L09wdXMgLT4gbWFpbiAoMTIyQikKICAgICJjbGF1ZGUtc29ubmV0LTQtNiI6ICAgICAgICAgICJtYWluIiwKICAgICJjbGF1ZGUtc29ubmV0LTQtNi0yMDI1MDUxNCI6ICJtYWluIiwKICAgICJjbGF1ZGUtb3B1cy00LTYiOiAgICAgICAgICAgICJtYWluIiwKICAgICJjbGF1ZGUtb3B1cy00LTYtMjAyNTA1MTQiOiAgICJtYWluIiwKICAgICJjbGF1ZGUtMy01LXNvbm5ldC0yMDI0MTAyMiI6ICJtYWluIiwKICAgICJjbGF1ZGUtMy01LXNvbm5ldC1sYXRlc3QiOiAgICJtYWluIiwKICAgICMgSGFpa3UgLT4gZmFzdCAoMzVCKQogICAgImNsYXVkZS1oYWlrdS00LTUtMjAyNTEwMDEiOiAgImZhc3QiLAogICAgImNsYXVkZS0zLTUtaGFpa3UtbGF0ZXN0IjogICAgImZhc3QiLAp9CgpERUZBVUxUX0JBQ0tFTkQgPSAibWFpbiIKCmRlZiBoYXNfaW1hZ2VzKG1lc3NhZ2VzKToKICAgICIiIkNoZWNrIGlmIGFueSBtZXNzYWdlIGNvbnRhaW5zIGltYWdlIGNvbnRlbnQiIiIKICAgIGZvciBtc2cgaW4gbWVzc2FnZXM6CiAgICAgICAgY29udGVudCA9IG1zZy5nZXQoImNvbnRlbnQiLCAiIikKICAgICAgICBpZiBpc2luc3RhbmNlKGNvbnRlbnQsIGxpc3QpOgogICAgICAgICAgICBmb3IgYmxvY2sgaW4gY29udGVudDoKICAgICAgICAgICAgICAgIGlmIGJsb2NrLmdldCgidHlwZSIpIGluICgiaW1hZ2UiLCAiaW1hZ2VfdXJsIik6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIFRydWUKICAgICAgICAgICAgICAgIGlmIGJsb2NrLmdldCgidHlwZSIpID09ICJzb3VyY2UiIGFuZCBibG9jay5nZXQoIm1lZGlhX3R5cGUiLCAiIikuc3RhcnRzd2l0aCgiaW1hZ2UvIik6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIFRydWUKICAgIHJldHVybiBGYWxzZQoKZGVmIGdldF9iYWNrZW5kKGFudGhyb3BpY19tb2RlbCwgbWVzc2FnZXM9Tm9uZSk6CiAgICAiIiJSZXNvbHZlIEFudGhyb3BpYyBtb2RlbCBuYW1lIHRvIE1MWCBiYWNrZW5kIGNvbmZpZy4KICAgIEF1dG8tcm91dGVzIHRvIHZpc2lvbiBiYWNrZW5kIGlmIGltYWdlcyBhcmUgZGV0ZWN0ZWQuIiIiCiAgICBpZiBtZXNzYWdlcyBhbmQgaGFzX2ltYWdlcyhtZXNzYWdlcyk6CiAgICAgICAgcmV0dXJuIE1PREVMUy5nZXQoInZpc2lvbiIsIE1PREVMU1sibWFpbiJdKQogICAga2V5ID0gTU9ERUxfUk9VVEVTLmdldChhbnRocm9waWNfbW9kZWwsIERFRkFVTFRfQkFDS0VORCkKICAgIGJhY2tlbmQgPSBNT0RFTFMuZ2V0KGtleSwgTU9ERUxTWyJtYWluIl0pCiAgICByZXR1cm4gYmFja2VuZAoKZGVmIGxvZyhtc2cpOgogICAgcHJpbnQoZiJbe3RpbWUuc3RyZnRpbWUoJyVIOiVNOiVTJyl9XSB7bXNnfSIsIGZsdXNoPVRydWUpCgojIOKUgOKUgCBBbnRocm9waWMg4oaSIE9wZW5BSSBjb252ZXJzaW9uIOKUgOKUgAoKZGVmIGNvbnZlcnRfdG9vbHMoYW50aHJvcGljX3Rvb2xzKToKICAgICIiIkFudGhyb3BpYyB0b29scyDihpIgT3BlbkFJIHRvb2xzIiIiCiAgICBpZiBub3QgYW50aHJvcGljX3Rvb2xzOgogICAgICAgIHJldHVybiBOb25lCiAgICBvYWlfdG9vbHMgPSBbXQogICAgZm9yIHQgaW4gYW50aHJvcGljX3Rvb2xzOgogICAgICAgIG9haV90b29scy5hcHBlbmQoewogICAgICAgICAgICAidHlwZSI6ICJmdW5jdGlvbiIsCiAgICAgICAgICAgICJmdW5jdGlvbiI6IHsKICAgICAgICAgICAgICAgICJuYW1lIjogdFsibmFtZSJdLAogICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogdC5nZXQoImRlc2NyaXB0aW9uIiwgIiIpLAogICAgICAgICAgICAgICAgInBhcmFtZXRlcnMiOiB0LmdldCgiaW5wdXRfc2NoZW1hIiwge30pLAogICAgICAgICAgICB9CiAgICAgICAgfSkKICAgIHJldHVybiBvYWlfdG9vbHMKCmRlZiBjb252ZXJ0X21lc3NhZ2VzKG1lc3NhZ2VzLCBzeXN0ZW09IiIpOgogICAgIiIiQW50aHJvcGljIG1lc3NhZ2VzIOKGkiBPcGVuQUkgbWVzc2FnZXMiIiIKICAgIG9haSA9IFtdCiAgICBpZiBzeXN0ZW06CiAgICAgICAgaWYgaXNpbnN0YW5jZShzeXN0ZW0sIGxpc3QpOgogICAgICAgICAgICBzeXN0ZW0gPSAiICIuam9pbihiLmdldCgidGV4dCIsIiIpIGZvciBiIGluIHN5c3RlbSBpZiBiLmdldCgidHlwZSIpPT0idGV4dCIpCiAgICAgICAgb2FpLmFwcGVuZCh7InJvbGUiOiAic3lzdGVtIiwgImNvbnRlbnQiOiBzeXN0ZW19KQoKICAgIGZvciBtc2cgaW4gbWVzc2FnZXM6CiAgICAgICAgcm9sZSA9IG1zZ1sicm9sZSJdCiAgICAgICAgY29udGVudCA9IG1zZy5nZXQoImNvbnRlbnQiLCAiIikKCiAgICAgICAgIyBTaW1wbGUgc3RyaW5nIGNvbnRlbnQKICAgICAgICBpZiBpc2luc3RhbmNlKGNvbnRlbnQsIHN0cik6CiAgICAgICAgICAgIG9haS5hcHBlbmQoeyJyb2xlIjogcm9sZSwgImNvbnRlbnQiOiBjb250ZW50fSkKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgIyBBcnJheSBjb250ZW50IOKAlCBuZWVkIHRvIHNwbGl0IGludG8gdGV4dCwgdG9vbF91c2UsIHRvb2xfcmVzdWx0LCBpbWFnZQogICAgICAgIGlmIGlzaW5zdGFuY2UoY29udGVudCwgbGlzdCk6CiAgICAgICAgICAgIHRleHRfcGFydHMgPSBbXQogICAgICAgICAgICBpbWFnZV9wYXJ0cyA9IFtdCiAgICAgICAgICAgIHRvb2xfY2FsbHMgPSBbXQogICAgICAgICAgICB0b29sX3Jlc3VsdHMgPSBbXQoKICAgICAgICAgICAgZm9yIGJsb2NrIGluIGNvbnRlbnQ6CiAgICAgICAgICAgICAgICBidHlwZSA9IGJsb2NrLmdldCgidHlwZSIsICIiKQogICAgICAgICAgICAgICAgaWYgYnR5cGUgPT0gInRleHQiOgogICAgICAgICAgICAgICAgICAgIHRleHRfcGFydHMuYXBwZW5kKGJsb2NrLmdldCgidGV4dCIsICIiKSkKICAgICAgICAgICAgICAgIGVsaWYgYnR5cGUgPT0gImltYWdlIjoKICAgICAgICAgICAgICAgICAgICAjIEFudGhyb3BpYyBpbWFnZSBibG9jazogeyJ0eXBlIjoiaW1hZ2UiLCJzb3VyY2UiOnsidHlwZSI6ImJhc2U2NCIsIm1lZGlhX3R5cGUiOiJpbWFnZS9qcGVnIiwiZGF0YSI6Ii4uLiJ9fQogICAgICAgICAgICAgICAgICAgIHNyYyA9IGJsb2NrLmdldCgic291cmNlIiwge30pCiAgICAgICAgICAgICAgICAgICAgaWYgc3JjLmdldCgidHlwZSIpID09ICJiYXNlNjQiOgogICAgICAgICAgICAgICAgICAgICAgICBkYXRhX3VybCA9IGYiZGF0YTp7c3JjLmdldCgnbWVkaWFfdHlwZScsJ2ltYWdlL2pwZWcnKX07YmFzZTY0LHtzcmNbJ2RhdGEnXX0iCiAgICAgICAgICAgICAgICAgICAgICAgIGltYWdlX3BhcnRzLmFwcGVuZCh7InR5cGUiOiAiaW1hZ2VfdXJsIiwgImltYWdlX3VybCI6IHsidXJsIjogZGF0YV91cmx9fSkKICAgICAgICAgICAgICAgICAgICBlbGlmIHNyYy5nZXQoInR5cGUiKSA9PSAidXJsIjoKICAgICAgICAgICAgICAgICAgICAgICAgaW1hZ2VfcGFydHMuYXBwZW5kKHsidHlwZSI6ICJpbWFnZV91cmwiLCAiaW1hZ2VfdXJsIjogeyJ1cmwiOiBzcmNbInVybCJdfX0pCiAgICAgICAgICAgICAgICBlbGlmIGJ0eXBlID09ICJpbWFnZV91cmwiOgogICAgICAgICAgICAgICAgICAgIGltYWdlX3BhcnRzLmFwcGVuZChibG9jaykKICAgICAgICAgICAgICAgIGVsaWYgYnR5cGUgPT0gInRvb2xfdXNlIjoKICAgICAgICAgICAgICAgICAgICB0b29sX2NhbGxzLmFwcGVuZCh7CiAgICAgICAgICAgICAgICAgICAgICAgICJpZCI6IGJsb2NrWyJpZCJdLAogICAgICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJmdW5jdGlvbiIsCiAgICAgICAgICAgICAgICAgICAgICAgICJmdW5jdGlvbiI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJuYW1lIjogYmxvY2tbIm5hbWUiXSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJhcmd1bWVudHMiOiBqc29uLmR1bXBzKGJsb2NrLmdldCgiaW5wdXQiLCB7fSkpLAogICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgIGVsaWYgYnR5cGUgPT0gInRvb2xfcmVzdWx0IjoKICAgICAgICAgICAgICAgICAgICAjIEV4dHJhY3QgdGV4dCBmcm9tIHRvb2xfcmVzdWx0IGNvbnRlbnQKICAgICAgICAgICAgICAgICAgICB0cl9jb250ZW50ID0gYmxvY2suZ2V0KCJjb250ZW50IiwgIiIpCiAgICAgICAgICAgICAgICAgICAgaWYgaXNpbnN0YW5jZSh0cl9jb250ZW50LCBsaXN0KToKICAgICAgICAgICAgICAgICAgICAgICAgdHJfY29udGVudCA9ICJcbiIuam9pbigKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGIuZ2V0KCJ0ZXh0IiwiIikgZm9yIGIgaW4gdHJfY29udGVudAogICAgICAgICAgICAgICAgICAgICAgICAgICAgaWYgaXNpbnN0YW5jZShiLCBkaWN0KSBhbmQgYi5nZXQoInR5cGUiKSA9PSAidGV4dCIKICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgIGVsaWYgbm90IGlzaW5zdGFuY2UodHJfY29udGVudCwgc3RyKToKICAgICAgICAgICAgICAgICAgICAgICAgdHJfY29udGVudCA9IHN0cih0cl9jb250ZW50KQogICAgICAgICAgICAgICAgICAgIHRvb2xfcmVzdWx0cy5hcHBlbmQoewogICAgICAgICAgICAgICAgICAgICAgICAicm9sZSI6ICJ0b29sIiwKICAgICAgICAgICAgICAgICAgICAgICAgInRvb2xfY2FsbF9pZCI6IGJsb2NrWyJ0b29sX3VzZV9pZCJdLAogICAgICAgICAgICAgICAgICAgICAgICAiY29udGVudCI6IHRyX2NvbnRlbnQsCiAgICAgICAgICAgICAgICAgICAgfSkKCiAgICAgICAgICAgIGlmIHJvbGUgPT0gImFzc2lzdGFudCI6CiAgICAgICAgICAgICAgICBtID0geyJyb2xlIjogImFzc2lzdGFudCJ9CiAgICAgICAgICAgICAgICBpZiB0ZXh0X3BhcnRzOgogICAgICAgICAgICAgICAgICAgIG1bImNvbnRlbnQiXSA9ICJcbiIuam9pbih0ZXh0X3BhcnRzKQogICAgICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgICAgICBtWyJjb250ZW50Il0gPSAiIgogICAgICAgICAgICAgICAgaWYgdG9vbF9jYWxsczoKICAgICAgICAgICAgICAgICAgICBtWyJ0b29sX2NhbGxzIl0gPSB0b29sX2NhbGxzCiAgICAgICAgICAgICAgICBvYWkuYXBwZW5kKG0pCiAgICAgICAgICAgIGVsaWYgcm9sZSA9PSAidXNlciI6CiAgICAgICAgICAgICAgICAjIFVzZXIgbWVzc2FnZXMgbWF5IGNvbnRhaW4gdGV4dCArIGltYWdlcyArIHRvb2xfcmVzdWx0cwogICAgICAgICAgICAgICAgaWYgaW1hZ2VfcGFydHM6CiAgICAgICAgICAgICAgICAgICAgIyBNdWx0aS1tb2RhbDogYnVpbGQgT3BlbkFJIGNvbnRlbnQgYXJyYXkgd2l0aCBpbWFnZXMgKyB0ZXh0CiAgICAgICAgICAgICAgICAgICAgbXVsdGlfY29udGVudCA9IGxpc3QoaW1hZ2VfcGFydHMpCiAgICAgICAgICAgICAgICAgICAgaWYgdGV4dF9wYXJ0czoKICAgICAgICAgICAgICAgICAgICAgICAgbXVsdGlfY29udGVudC5hcHBlbmQoeyJ0eXBlIjogInRleHQiLCAidGV4dCI6ICJcbiIuam9pbih0ZXh0X3BhcnRzKX0pCiAgICAgICAgICAgICAgICAgICAgb2FpLmFwcGVuZCh7InJvbGUiOiAidXNlciIsICJjb250ZW50IjogbXVsdGlfY29udGVudH0pCiAgICAgICAgICAgICAgICBlbGlmIHRleHRfcGFydHM6CiAgICAgICAgICAgICAgICAgICAgb2FpLmFwcGVuZCh7InJvbGUiOiAidXNlciIsICJjb250ZW50IjogIlxuIi5qb2luKHRleHRfcGFydHMpfSkKICAgICAgICAgICAgICAgIGZvciB0ciBpbiB0b29sX3Jlc3VsdHM6CiAgICAgICAgICAgICAgICAgICAgb2FpLmFwcGVuZCh0cikKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIG9haS5hcHBlbmQoeyJyb2xlIjogcm9sZSwgImNvbnRlbnQiOiBzdHIoY29udGVudCl9KQoKICAgIHJldHVybiBvYWkKCiMg4pSA4pSAIE9wZW5BSSDihpIgQW50aHJvcGljIGNvbnZlcnNpb24g4pSA4pSACgpkZWYgb2FpX3Jlc3BvbnNlX3RvX2FudGhyb3BpYyhkYXRhLCBtb2RlbCk6CiAgICAiIiJDb252ZXJ0IE9wZW5BSSBjb21wbGV0aW9uIHJlc3BvbnNlIHRvIEFudGhyb3BpYyBtZXNzYWdlIHJlc3BvbnNlIiIiCiAgICBjaG9pY2UgPSBkYXRhLmdldCgiY2hvaWNlcyIsIFt7fV0pWzBdCiAgICBtZXNzYWdlID0gY2hvaWNlLmdldCgibWVzc2FnZSIsIHt9KQogICAgdXNhZ2UgPSBkYXRhLmdldCgidXNhZ2UiLCB7fSkKICAgIGZpbmlzaCA9IGNob2ljZS5nZXQoImZpbmlzaF9yZWFzb24iLCAic3RvcCIpCgogICAgY29udGVudF9ibG9ja3MgPSBbXQoKICAgICMgVGV4dCBjb250ZW50CiAgICB0ZXh0ID0gbWVzc2FnZS5nZXQoImNvbnRlbnQiLCAiIikKICAgIGlmIHRleHQ6CiAgICAgICAgY29udGVudF9ibG9ja3MuYXBwZW5kKHsidHlwZSI6ICJ0ZXh0IiwgInRleHQiOiB0ZXh0fSkKCiAgICAjIFRvb2wgY2FsbHMKICAgIGZvciB0YyBpbiBtZXNzYWdlLmdldCgidG9vbF9jYWxscyIsIFtdKToKICAgICAgICBmdW5jID0gdGMuZ2V0KCJmdW5jdGlvbiIsIHt9KQogICAgICAgIHRyeToKICAgICAgICAgICAgaW5wdXRfZGF0YSA9IGpzb24ubG9hZHMoZnVuYy5nZXQoImFyZ3VtZW50cyIsICJ7fSIpKQogICAgICAgIGV4Y2VwdCBqc29uLkpTT05EZWNvZGVFcnJvcjoKICAgICAgICAgICAgaW5wdXRfZGF0YSA9IHt9CiAgICAgICAgY29udGVudF9ibG9ja3MuYXBwZW5kKHsKICAgICAgICAgICAgInR5cGUiOiAidG9vbF91c2UiLAogICAgICAgICAgICAiaWQiOiBmInRvb2x1X3t1dWlkLnV1aWQ0KCkuaGV4WzoyNF19IiwKICAgICAgICAgICAgIm5hbWUiOiBmdW5jLmdldCgibmFtZSIsICIiKSwKICAgICAgICAgICAgImlucHV0IjogaW5wdXRfZGF0YSwKICAgICAgICB9KQoKICAgICMgRGV0ZXJtaW5lIHN0b3AgcmVhc29uCiAgICBpZiBmaW5pc2ggPT0gInRvb2xfY2FsbHMiOgogICAgICAgIHN0b3BfcmVhc29uID0gInRvb2xfdXNlIgogICAgZWxzZToKICAgICAgICBzdG9wX3JlYXNvbiA9ICJlbmRfdHVybiIKCiAgICByZXR1cm4gewogICAgICAgICJpZCI6IGYibXNnX3t1dWlkLnV1aWQ0KCkuaGV4WzoyNF19IiwKICAgICAgICAidHlwZSI6ICJtZXNzYWdlIiwKICAgICAgICAicm9sZSI6ICJhc3Npc3RhbnQiLAogICAgICAgICJtb2RlbCI6IG1vZGVsLAogICAgICAgICJjb250ZW50IjogY29udGVudF9ibG9ja3MgaWYgY29udGVudF9ibG9ja3MgZWxzZSBbeyJ0eXBlIjogInRleHQiLCAidGV4dCI6ICIifV0sCiAgICAgICAgInN0b3BfcmVhc29uIjogc3RvcF9yZWFzb24sCiAgICAgICAgInN0b3Bfc2VxdWVuY2UiOiBOb25lLAogICAgICAgICJ1c2FnZSI6IHsKICAgICAgICAgICAgImlucHV0X3Rva2VucyI6IHVzYWdlLmdldCgicHJvbXB0X3Rva2VucyIsIDApLAogICAgICAgICAgICAib3V0cHV0X3Rva2VucyI6IHVzYWdlLmdldCgiY29tcGxldGlvbl90b2tlbnMiLCAwKSwKICAgICAgICAgICAgImNhY2hlX2NyZWF0aW9uX2lucHV0X3Rva2VucyI6IDAsCiAgICAgICAgICAgICJjYWNoZV9yZWFkX2lucHV0X3Rva2VucyI6IDAsCiAgICAgICAgfQogICAgfQoKIyDilIDilIAgSGFuZGxlcnMg4pSA4pSACgphc3luYyBkZWYgaGFuZGxlX21lc3NhZ2VzKHJlcXVlc3QpOgogICAgYm9keSA9IGF3YWl0IHJlcXVlc3QuanNvbigpCiAgICBtb2RlbCA9IGJvZHkuZ2V0KCJtb2RlbCIsICJjbGF1ZGUtc29ubmV0LTQtNiIpCiAgICBzdHJlYW0gPSBib2R5LmdldCgic3RyZWFtIiwgRmFsc2UpCiAgICB0b29scyA9IGJvZHkuZ2V0KCJ0b29scyIsIE5vbmUpCiAgICBiYWNrZW5kID0gZ2V0X2JhY2tlbmQobW9kZWwsIGJvZHkuZ2V0KCJtZXNzYWdlcyIsIFtdKSkKICAgIG1seF91cmwgPSBmImh0dHA6Ly8xMjcuMC4wLjE6e2JhY2tlbmRbJ3BvcnQnXX0vdjEvY2hhdC9jb21wbGV0aW9ucyIKICAgIGxvZyhmIlBPU1QgL3YxL21lc3NhZ2VzIG1vZGVsPXttb2RlbH0gLT4ge2JhY2tlbmRbJ2xhYmVsJ119IDp7YmFja2VuZFsncG9ydCddfSBzdHJlYW09e3N0cmVhbX0gdG9vbHM9e2xlbih0b29scykgaWYgdG9vbHMgZWxzZSAwfSIpCgogICAgb2FpX2JvZHkgPSB7CiAgICAgICAgIm1vZGVsIjogYmFja2VuZFsibWx4X21vZGVsIl0sCiAgICAgICAgIm1lc3NhZ2VzIjogY29udmVydF9tZXNzYWdlcyhib2R5LmdldCgibWVzc2FnZXMiLCBbXSksIGJvZHkuZ2V0KCJzeXN0ZW0iLCAiIikpLAogICAgICAgICJtYXhfdG9rZW5zIjogYm9keS5nZXQoIm1heF90b2tlbnMiLCA0MDk2KSwKICAgICAgICAiY2hhdF90ZW1wbGF0ZV9rd2FyZ3MiOiB7ImVuYWJsZV90aGlua2luZyI6IEZhbHNlfSwKICAgIH0KICAgIGlmIGJvZHkuZ2V0KCJ0ZW1wZXJhdHVyZSIpIGlzIG5vdCBOb25lOgogICAgICAgIG9haV9ib2R5WyJ0ZW1wZXJhdHVyZSJdID0gYm9keVsidGVtcGVyYXR1cmUiXQogICAgaWYgdG9vbHM6CiAgICAgICAgb2FpX2JvZHlbInRvb2xzIl0gPSBjb252ZXJ0X3Rvb2xzKHRvb2xzKQoKICAgIGlmIHN0cmVhbToKICAgICAgICByZXR1cm4gYXdhaXQgaGFuZGxlX3N0cmVhbShyZXF1ZXN0LCBvYWlfYm9keSwgbW9kZWwsIG1seF91cmwpCgogICAgIyBOb24tc3RyZWFtaW5nCiAgICBhc3luYyB3aXRoIENsaWVudFNlc3Npb24oKSBhcyBzZXNzaW9uOgogICAgICAgIGFzeW5jIHdpdGggc2Vzc2lvbi5wb3N0KG1seF91cmwsIGpzb249b2FpX2JvZHkpIGFzIHJlc3A6CiAgICAgICAgICAgIGRhdGEgPSBhd2FpdCByZXNwLmpzb24oKQoKICAgIHJldHVybiB3ZWIuanNvbl9yZXNwb25zZShvYWlfcmVzcG9uc2VfdG9fYW50aHJvcGljKGRhdGEsIG1vZGVsKSkKCmFzeW5jIGRlZiBoYW5kbGVfc3RyZWFtKHJlcXVlc3QsIG9haV9ib2R5LCBtb2RlbCwgbWx4X3VybCk6CiAgICBtc2dfaWQgPSBmIm1zZ197dXVpZC51dWlkNCgpLmhleFs6MjRdfSIKICAgIHJlc3BvbnNlID0gd2ViLlN0cmVhbVJlc3BvbnNlKCkKICAgIHJlc3BvbnNlLmhlYWRlcnNbIkNvbnRlbnQtVHlwZSJdID0gInRleHQvZXZlbnQtc3RyZWFtIgogICAgcmVzcG9uc2UuaGVhZGVyc1siQ2FjaGUtQ29udHJvbCJdID0gIm5vLWNhY2hlIgogICAgYXdhaXQgcmVzcG9uc2UucHJlcGFyZShyZXF1ZXN0KQoKICAgIGFzeW5jIGRlZiBzZW5kKGV2ZW50X3R5cGUsIGRhdGEpOgogICAgICAgIGF3YWl0IHJlc3BvbnNlLndyaXRlKGYiZXZlbnQ6IHtldmVudF90eXBlfVxuZGF0YToge2pzb24uZHVtcHMoZGF0YSl9XG5cbiIuZW5jb2RlKCkpCgogICAgIyBtZXNzYWdlX3N0YXJ0CiAgICBhd2FpdCBzZW5kKCJtZXNzYWdlX3N0YXJ0IiwgewogICAgICAgICJ0eXBlIjogIm1lc3NhZ2Vfc3RhcnQiLAogICAgICAgICJtZXNzYWdlIjogewogICAgICAgICAgICAiaWQiOiBtc2dfaWQsICJ0eXBlIjogIm1lc3NhZ2UiLCAicm9sZSI6ICJhc3Npc3RhbnQiLAogICAgICAgICAgICAibW9kZWwiOiBtb2RlbCwgImNvbnRlbnQiOiBbXSwgInN0b3BfcmVhc29uIjogTm9uZSwgInN0b3Bfc2VxdWVuY2UiOiBOb25lLAogICAgICAgICAgICAidXNhZ2UiOiB7ImlucHV0X3Rva2VucyI6IDAsICJvdXRwdXRfdG9rZW5zIjogMCwKICAgICAgICAgICAgICAgICAgICAgICJjYWNoZV9jcmVhdGlvbl9pbnB1dF90b2tlbnMiOiAwLCAiY2FjaGVfcmVhZF9pbnB1dF90b2tlbnMiOiAwfQogICAgICAgIH0KICAgIH0pCgogICAgb2FpX2JvZHlbInN0cmVhbSJdID0gVHJ1ZQogICAgZnVsbF90ZXh0ID0gIiIKICAgICMgVHJhY2sgdG9vbCBjYWxscyBiZWluZyBzdHJlYW1lZDoge2luZGV4OiB7aWQsIG5hbWUsIGFyZ3VtZW50c319CiAgICB0b29sX2NhbGxzID0ge30KICAgIGNvbnRlbnRfaW5kZXggPSAwICAjIE5leHQgQW50aHJvcGljIGNvbnRlbnQgYmxvY2sgaW5kZXgKICAgIHRleHRfYmxvY2tfc3RhcnRlZCA9IEZhbHNlCiAgICB0b29sX2Jsb2Nrc19zdGFydGVkID0ge30gICMgaW5kZXggLT4gYm9vbAoKICAgIGFzeW5jIHdpdGggQ2xpZW50U2Vzc2lvbigpIGFzIHNlc3Npb246CiAgICAgICAgYXN5bmMgd2l0aCBzZXNzaW9uLnBvc3QobWx4X3VybCwganNvbj1vYWlfYm9keSkgYXMgcmVzcDoKICAgICAgICAgICAgYXN5bmMgZm9yIGxpbmUgaW4gcmVzcC5jb250ZW50OgogICAgICAgICAgICAgICAgbGluZSA9IGxpbmUuZGVjb2RlKCkuc3RyaXAoKQogICAgICAgICAgICAgICAgaWYgbm90IGxpbmUuc3RhcnRzd2l0aCgiZGF0YTogIik6CiAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgIGRhdGFfc3RyID0gbGluZVs2Ol0KICAgICAgICAgICAgICAgIGlmIGRhdGFfc3RyID09ICJbRE9ORV0iOgogICAgICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgY2h1bmsgPSBqc29uLmxvYWRzKGRhdGFfc3RyKQogICAgICAgICAgICAgICAgICAgIGRlbHRhID0gY2h1bmsuZ2V0KCJjaG9pY2VzIiwgW3t9XSlbMF0uZ2V0KCJkZWx0YSIsIHt9KQoKICAgICAgICAgICAgICAgICAgICAjIFRleHQgY29udGVudAogICAgICAgICAgICAgICAgICAgIHRleHQgPSBkZWx0YS5nZXQoImNvbnRlbnQiLCAiIikKICAgICAgICAgICAgICAgICAgICBpZiB0ZXh0OgogICAgICAgICAgICAgICAgICAgICAgICBpZiBub3QgdGV4dF9ibG9ja19zdGFydGVkOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgYXdhaXQgc2VuZCgiY29udGVudF9ibG9ja19zdGFydCIsIHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJjb250ZW50X2Jsb2NrX3N0YXJ0IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiaW5kZXgiOiBjb250ZW50X2luZGV4LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJjb250ZW50X2Jsb2NrIjogeyJ0eXBlIjogInRleHQiLCAidGV4dCI6ICIifQogICAgICAgICAgICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRleHRfYmxvY2tfc3RhcnRlZCA9IFRydWUKICAgICAgICAgICAgICAgICAgICAgICAgZnVsbF90ZXh0ICs9IHRleHQKICAgICAgICAgICAgICAgICAgICAgICAgYXdhaXQgc2VuZCgiY29udGVudF9ibG9ja19kZWx0YSIsIHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogImNvbnRlbnRfYmxvY2tfZGVsdGEiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgImluZGV4IjogY29udGVudF9pbmRleCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJkZWx0YSI6IHsidHlwZSI6ICJ0ZXh0X2RlbHRhIiwgInRleHQiOiB0ZXh0fQogICAgICAgICAgICAgICAgICAgICAgICB9KQoKICAgICAgICAgICAgICAgICAgICAjIFRvb2wgY2FsbHMKICAgICAgICAgICAgICAgICAgICBmb3IgdGMgaW4gZGVsdGEuZ2V0KCJ0b29sX2NhbGxzIiwgW10pOgogICAgICAgICAgICAgICAgICAgICAgICBpZHggPSB0Yy5nZXQoImluZGV4IiwgMCkKICAgICAgICAgICAgICAgICAgICAgICAgaWYgaWR4IG5vdCBpbiB0b29sX2NhbGxzOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgdG9vbF9jYWxsc1tpZHhdID0gewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJpZCI6IHRjLmdldCgiaWQiLCBmInRvb2x1X3t1dWlkLnV1aWQ0KCkuaGV4WzoyNF19IiksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIm5hbWUiOiB0Yy5nZXQoImZ1bmN0aW9uIiwge30pLmdldCgibmFtZSIsICIiKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiYXJndW1lbnRzIjogIiIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAjIEFjY3VtdWxhdGUgYXJndW1lbnRzCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0b29sX2NhbGxzW2lkeF1bImFyZ3VtZW50cyJdICs9IHRjLmdldCgiZnVuY3Rpb24iLCB7fSkuZ2V0KCJhcmd1bWVudHMiLCAiIikKCiAgICAgICAgICAgICAgICAgICAgICAgIGZ1bmMgPSB0Yy5nZXQoImZ1bmN0aW9uIiwge30pCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIGZ1bmMuZ2V0KCJuYW1lIikgYW5kIGlkeCBub3QgaW4gdG9vbF9ibG9ja3Nfc3RhcnRlZDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICMgQ2xvc2UgdGV4dCBibG9jayBpZiBvcGVuCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZiB0ZXh0X2Jsb2NrX3N0YXJ0ZWQ6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYXdhaXQgc2VuZCgiY29udGVudF9ibG9ja19zdG9wIiwgewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAidHlwZSI6ICJjb250ZW50X2Jsb2NrX3N0b3AiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiaW5kZXgiOiBjb250ZW50X2luZGV4CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb250ZW50X2luZGV4ICs9IDEKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB0ZXh0X2Jsb2NrX3N0YXJ0ZWQgPSBGYWxzZQoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICMgU3RhcnQgdG9vbF91c2UgYmxvY2sKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRvb2xfYmxvY2tzX3N0YXJ0ZWRbaWR4XSA9IGNvbnRlbnRfaW5kZXgKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGF3YWl0IHNlbmQoImNvbnRlbnRfYmxvY2tfc3RhcnQiLCB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAiY29udGVudF9ibG9ja19zdGFydCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImluZGV4IjogY29udGVudF9pbmRleCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiY29udGVudF9ibG9jayI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAidG9vbF91c2UiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiaWQiOiBmInRvb2x1X3t1dWlkLnV1aWQ0KCkuaGV4WzoyNF19IiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIm5hbWUiOiBmdW5jWyJuYW1lIl0sCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJpbnB1dCI6IHt9CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICMgU3RvcmUgdGhlIHRvb2x1X2lkIGZvciB0aGlzIGJsb2NrCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0b29sX2NhbGxzW2lkeF1bImJsb2NrX2luZGV4Il0gPSBjb250ZW50X2luZGV4CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBjb250ZW50X2luZGV4ICs9IDEKCiAgICAgICAgICAgICAgICAgICAgICAgIGlmIGZ1bmMuZ2V0KCJhcmd1bWVudHMiKToKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGJsb2NrX2lkeCA9IHRvb2xfY2FsbHNbaWR4XS5nZXQoImJsb2NrX2luZGV4IiwgY29udGVudF9pbmRleCAtIDEpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBhd2FpdCBzZW5kKCJjb250ZW50X2Jsb2NrX2RlbHRhIiwgewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogImNvbnRlbnRfYmxvY2tfZGVsdGEiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJpbmRleCI6IGJsb2NrX2lkeCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAiZGVsdGEiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0eXBlIjogImlucHV0X2pzb25fZGVsdGEiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAicGFydGlhbF9qc29uIjogZnVuY1siYXJndW1lbnRzIl0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgICAgICAgICB9KQogICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICAgICAgICAgIGxvZyhmIlN0cmVhbSBwYXJzZSBlcnJvcjoge2V9IikKCiAgICAjIENsb3NlIG9wZW4gYmxvY2tzCiAgICBpZiB0ZXh0X2Jsb2NrX3N0YXJ0ZWQ6CiAgICAgICAgYXdhaXQgc2VuZCgiY29udGVudF9ibG9ja19zdG9wIiwgeyJ0eXBlIjogImNvbnRlbnRfYmxvY2tfc3RvcCIsICJpbmRleCI6IDB9KQoKICAgIGZvciBpZHgsIHRjIGluIHRvb2xfY2FsbHMuaXRlbXMoKToKICAgICAgICBibG9ja19pZHggPSB0Yy5nZXQoImJsb2NrX2luZGV4IiwgaWR4ICsgMSkKICAgICAgICBhd2FpdCBzZW5kKCJjb250ZW50X2Jsb2NrX3N0b3AiLCB7InR5cGUiOiAiY29udGVudF9ibG9ja19zdG9wIiwgImluZGV4IjogYmxvY2tfaWR4fSkKCiAgICAjIERldGVybWluZSBzdG9wIHJlYXNvbgogICAgc3RvcF9yZWFzb24gPSAidG9vbF91c2UiIGlmIHRvb2xfY2FsbHMgZWxzZSAiZW5kX3R1cm4iCgogICAgYXdhaXQgc2VuZCgibWVzc2FnZV9kZWx0YSIsIHsKICAgICAgICAidHlwZSI6ICJtZXNzYWdlX2RlbHRhIiwKICAgICAgICAiZGVsdGEiOiB7InN0b3BfcmVhc29uIjogc3RvcF9yZWFzb24sICJzdG9wX3NlcXVlbmNlIjogTm9uZX0sCiAgICAgICAgInVzYWdlIjogeyJvdXRwdXRfdG9rZW5zIjogbGVuKGZ1bGxfdGV4dCkgLy8gNCArIHN1bShsZW4odGNbImFyZ3VtZW50cyJdKSAvLyA0IGZvciB0YyBpbiB0b29sX2NhbGxzLnZhbHVlcygpKX0KICAgIH0pCiAgICBhd2FpdCBzZW5kKCJtZXNzYWdlX3N0b3AiLCB7InR5cGUiOiAibWVzc2FnZV9zdG9wIn0pCgogICAgYXdhaXQgcmVzcG9uc2Uud3JpdGVfZW9mKCkKICAgIHJldHVybiByZXNwb25zZQoKYXN5bmMgZGVmIGhhbmRsZV9jb3VudF90b2tlbnMocmVxdWVzdCk6CiAgICBib2R5ID0gYXdhaXQgcmVxdWVzdC5qc29uKCkKICAgIGxvZyhmIlBPU1QgL3YxL21lc3NhZ2VzL2NvdW50X3Rva2VucyIpCiAgICBtc2dzID0gY29udmVydF9tZXNzYWdlcyhib2R5LmdldCgibWVzc2FnZXMiLCBbXSksIGJvZHkuZ2V0KCJzeXN0ZW0iLCAiIikpCiAgICB0b3RhbCA9IHN1bShsZW4obS5nZXQoImNvbnRlbnQiLCAiIikpIC8vIDQgZm9yIG0gaW4gbXNncykKICAgIHJldHVybiB3ZWIuanNvbl9yZXNwb25zZSh7ImlucHV0X3Rva2VucyI6IHRvdGFsfSkKCmFzeW5jIGRlZiBoYW5kbGVfbW9kZWxzKHJlcXVlc3QpOgogICAgbG9nKGYiR0VUIC92MS9tb2RlbHMiKQogICAgcmV0dXJuIHdlYi5qc29uX3Jlc3BvbnNlKHsKICAgICAgICAiZGF0YSI6IFt7ImlkIjogbSwgIm9iamVjdCI6ICJtb2RlbCIsICJjcmVhdGVkIjogMTY3NzYxMDYwMiwgIm93bmVkX2J5IjogImFudGhyb3BpYyJ9CiAgICAgICAgICAgICAgICAgZm9yIG0gaW4gTU9ERUxfUk9VVEVTLmtleXMoKV0sCiAgICAgICAgIm9iamVjdCI6ICJsaXN0IgogICAgfSkKCmFzeW5jIGRlZiBjYXRjaF9hbGwocmVxdWVzdCk6CiAgICBib2R5ID0gYXdhaXQgcmVxdWVzdC50ZXh0KCkKICAgIGxvZyhmIkNBVENILUFMTCB7cmVxdWVzdC5tZXRob2R9IHtyZXF1ZXN0LnBhdGh9IGJvZHk9e2JvZHlbOjMwMF19IikKICAgIHJldHVybiB3ZWIuanNvbl9yZXNwb25zZSh7Im9rIjogVHJ1ZX0pCgphcHAgPSB3ZWIuQXBwbGljYXRpb24oKQphcHAucm91dGVyLmFkZF9wb3N0KCIvdjEvbWVzc2FnZXMvY291bnRfdG9rZW5zIiwgaGFuZGxlX2NvdW50X3Rva2VucykKYXBwLnJvdXRlci5hZGRfcG9zdCgiL3YxL21lc3NhZ2VzIiwgaGFuZGxlX21lc3NhZ2VzKQphcHAucm91dGVyLmFkZF9nZXQoIi92MS9tb2RlbHMiLCBoYW5kbGVfbW9kZWxzKQphcHAucm91dGVyLmFkZF9yb3V0ZSgiKiIsICIve3BhdGg6Lip9IiwgY2F0Y2hfYWxsKQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIGZvciBuYW1lLCBjZmcgaW4gTU9ERUxTLml0ZW1zKCk6CiAgICAgICAgbG9nKGYiICBbe25hbWV9XSB7Y2ZnWydtbHhfbW9kZWwnXX0gLT4gOntjZmdbJ3BvcnQnXX0gKHtjZmdbJ2xhYmVsJ119KSIpCiAgICBsb2coZiJBbnRocm9waWMgcHJveHkgb24gOjQwMDEgKG11bHRpLW1vZGVsLCB0b29sX3VzZSkiKQogICAgd2ViLnJ1bl9hcHAoYXBwLCBob3N0PSIwLjAuMC4wIiwgcG9ydD00MDAxLCBwcmludD1sYW1iZGEgeDogbG9nKHgpKQo=
B64EOF

echo "[4b/6] Writing VLM server..."
base64 -d << 'VLM_B64EOF' > "$HOME/vlm_server.py"
IiIiVkxNIHNlcnZlciB1c2luZyBtbHgtdmxtIiIiCmltcG9ydCBqc29uLCB0aW1lLCBiYXNlNjQsIHRlbXBmaWxlLCBvcwpmcm9tIGFpb2h0dHAgaW1wb3J0IHdlYiwgQ2xpZW50U2Vzc2lvbgoKTU9ERUxfSUQgPSAibWx4LWNvbW11bml0eS9Rd2VuMy1WTC04Qi1JbnN0cnVjdC00Yml0IgoKZGVmIGxvZyhtc2cpOgogICAgcHJpbnQoZiJbe3RpbWUuc3RyZnRpbWUoJyVIOiVNOiVTJyl9XSBWTE06IHttc2d9IiwgZmx1c2g9VHJ1ZSkKCiMgTG9hZCBtb2RlbCBhdCBpbXBvcnQgdGltZSAoYmVmb3JlIHNlcnZlciBzdGFydHMpCmxvZyhmIkxvYWRpbmcge01PREVMX0lEfS4uLiIpCmZyb20gbWx4X3ZsbSBpbXBvcnQgbG9hZCwgZ2VuZXJhdGUsIGFwcGx5X2NoYXRfdGVtcGxhdGUKbW9kZWwsIHByb2Nlc3NvciA9IGxvYWQoTU9ERUxfSUQpCmxvZygiTW9kZWwgbG9hZGVkIikKCmFzeW5jIGRlZiBkb3dubG9hZF9pbWFnZSh1cmwpOgogICAgYXN5bmMgd2l0aCBDbGllbnRTZXNzaW9uKCkgYXMgc2Vzc2lvbjoKICAgICAgICBhc3luYyB3aXRoIHNlc3Npb24uZ2V0KHVybCwgaGVhZGVycz17IlVzZXItQWdlbnQiOiAiTW96aWxsYS81LjAifSkgYXMgcmVzcDoKICAgICAgICAgICAgZGF0YSA9IGF3YWl0IHJlc3AucmVhZCgpCiAgICAgICAgICAgIHRtcCA9IHRlbXBmaWxlLk5hbWVkVGVtcG9yYXJ5RmlsZShzdWZmaXg9Ii5qcGciLCBkZWxldGU9RmFsc2UpCiAgICAgICAgICAgIHRtcC53cml0ZShkYXRhKQogICAgICAgICAgICB0bXAuY2xvc2UoKQogICAgICAgICAgICByZXR1cm4gdG1wLm5hbWUKCmFzeW5jIGRlZiBoYW5kbGVfY2hhdChyZXF1ZXN0KToKICAgIGJvZHkgPSBhd2FpdCByZXF1ZXN0Lmpzb24oKQogICAgbWVzc2FnZXMgPSBib2R5LmdldCgibWVzc2FnZXMiLCBbXSkKICAgIG1heF90b2tlbnMgPSBib2R5LmdldCgibWF4X3Rva2VucyIsIDI1NikKCiAgICBpbWFnZXMgPSBbXQogICAgdGV4dF9wYXJ0cyA9IFtdCiAgICB0ZW1wX2ZpbGVzID0gW10KCiAgICBmb3IgbXNnIGluIG1lc3NhZ2VzOgogICAgICAgIGNvbnRlbnQgPSBtc2cuZ2V0KCJjb250ZW50IiwgIiIpCiAgICAgICAgaWYgaXNpbnN0YW5jZShjb250ZW50LCBzdHIpOgogICAgICAgICAgICB0ZXh0X3BhcnRzLmFwcGVuZChjb250ZW50KQogICAgICAgIGVsaWYgaXNpbnN0YW5jZShjb250ZW50LCBsaXN0KToKICAgICAgICAgICAgZm9yIGJsb2NrIGluIGNvbnRlbnQ6CiAgICAgICAgICAgICAgICBidHlwZSA9IGJsb2NrLmdldCgidHlwZSIsICIiKQogICAgICAgICAgICAgICAgaWYgYnR5cGUgPT0gInRleHQiOgogICAgICAgICAgICAgICAgICAgIHRleHRfcGFydHMuYXBwZW5kKGJsb2NrWyJ0ZXh0Il0pCiAgICAgICAgICAgICAgICBlbGlmIGJ0eXBlID09ICJpbWFnZV91cmwiOgogICAgICAgICAgICAgICAgICAgIHVybCA9IGJsb2NrWyJpbWFnZV91cmwiXVsidXJsIl0KICAgICAgICAgICAgICAgICAgICBpZiB1cmwuc3RhcnRzd2l0aCgiZGF0YToiKToKICAgICAgICAgICAgICAgICAgICAgICAgXywgYjY0ZGF0YSA9IHVybC5zcGxpdCgiLCIsIDEpCiAgICAgICAgICAgICAgICAgICAgICAgIHRtcCA9IHRlbXBmaWxlLk5hbWVkVGVtcG9yYXJ5RmlsZShzdWZmaXg9Ii5qcGciLCBkZWxldGU9RmFsc2UpCiAgICAgICAgICAgICAgICAgICAgICAgIHRtcC53cml0ZShiYXNlNjQuYjY0ZGVjb2RlKGI2NGRhdGEpKQogICAgICAgICAgICAgICAgICAgICAgICB0bXAuY2xvc2UoKQogICAgICAgICAgICAgICAgICAgICAgICBpbWFnZXMuYXBwZW5kKHRtcC5uYW1lKQogICAgICAgICAgICAgICAgICAgICAgICB0ZW1wX2ZpbGVzLmFwcGVuZCh0bXAubmFtZSkKICAgICAgICAgICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgICAgICAgICBwYXRoID0gYXdhaXQgZG93bmxvYWRfaW1hZ2UodXJsKQogICAgICAgICAgICAgICAgICAgICAgICBpbWFnZXMuYXBwZW5kKHBhdGgpCiAgICAgICAgICAgICAgICAgICAgICAgIHRlbXBfZmlsZXMuYXBwZW5kKHBhdGgpCiAgICAgICAgICAgICAgICBlbGlmIGJ0eXBlID09ICJpbWFnZSIgYW5kIGJsb2NrLmdldCgic291cmNlIiwge30pLmdldCgidHlwZSIpID09ICJiYXNlNjQiOgogICAgICAgICAgICAgICAgICAgIHRtcCA9IHRlbXBmaWxlLk5hbWVkVGVtcG9yYXJ5RmlsZShzdWZmaXg9Ii5qcGciLCBkZWxldGU9RmFsc2UpCiAgICAgICAgICAgICAgICAgICAgdG1wLndyaXRlKGJhc2U2NC5iNjRkZWNvZGUoYmxvY2tbInNvdXJjZSJdWyJkYXRhIl0pKQogICAgICAgICAgICAgICAgICAgIHRtcC5jbG9zZSgpCiAgICAgICAgICAgICAgICAgICAgaW1hZ2VzLmFwcGVuZCh0bXAubmFtZSkKICAgICAgICAgICAgICAgICAgICB0ZW1wX2ZpbGVzLmFwcGVuZCh0bXAubmFtZSkKCiAgICBwcm9tcHQgPSAiXG4iLmpvaW4odGV4dF9wYXJ0cykgb3IgIkRlc2NyaWJlIHRoaXMgaW1hZ2UuIgogICAgbG9nKGYiaW1hZ2VzPXtsZW4oaW1hZ2VzKX0gcHJvbXB0PXtwcm9tcHRbOjgwXX0iKQoKICAgIHRyeToKICAgICAgICBmb3JtYXR0ZWQgPSBhcHBseV9jaGF0X3RlbXBsYXRlKHByb2Nlc3NvciwgbW9kZWwuY29uZmlnLCBwcm9tcHQsIG51bV9pbWFnZXM9bGVuKGltYWdlcykpCiAgICAgICAgaW1nX2FyZyA9IGltYWdlcyBpZiBsZW4oaW1hZ2VzKSA+IDEgZWxzZSAoaW1hZ2VzWzBdIGlmIGltYWdlcyBlbHNlIE5vbmUpCiAgICAgICAgcmVzdWx0ID0gZ2VuZXJhdGUobW9kZWwsIHByb2Nlc3NvciwgZm9ybWF0dGVkLCBpbWFnZT1pbWdfYXJnLCBtYXhfdG9rZW5zPW1heF90b2tlbnMsIHZlcmJvc2U9RmFsc2UpCiAgICAgICAgb3V0cHV0ID0gcmVzdWx0LnRleHQgaWYgaGFzYXR0cihyZXN1bHQsICJ0ZXh0IikgZWxzZSBzdHIocmVzdWx0KQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIGxvZyhmIkVycm9yOiB7ZX0iKQogICAgICAgIGltcG9ydCB0cmFjZWJhY2s7IHRyYWNlYmFjay5wcmludF9leGMoKQogICAgICAgIG91dHB1dCA9IGYiRXJyb3I6IHtlfSIKCiAgICBmb3IgZiBpbiB0ZW1wX2ZpbGVzOgogICAgICAgIHRyeTogb3MudW5saW5rKGYpCiAgICAgICAgZXhjZXB0OiBwYXNzCgogICAgcmV0dXJuIHdlYi5qc29uX3Jlc3BvbnNlKHsKICAgICAgICAiaWQiOiAiY2hhdGNtcGwtdmxtIiwgIm9iamVjdCI6ICJjaGF0LmNvbXBsZXRpb24iLCAibW9kZWwiOiBNT0RFTF9JRCwKICAgICAgICAiY2hvaWNlcyI6IFt7ImluZGV4IjogMCwgImZpbmlzaF9yZWFzb24iOiAic3RvcCIsCiAgICAgICAgICAgICAgICAgICAgICJtZXNzYWdlIjogeyJyb2xlIjogImFzc2lzdGFudCIsICJjb250ZW50Ijogb3V0cHV0fX1dLAogICAgICAgICJ1c2FnZSI6IHsicHJvbXB0X3Rva2VucyI6IDAsICJjb21wbGV0aW9uX3Rva2VucyI6IGxlbihvdXRwdXQpLy80LCAidG90YWxfdG9rZW5zIjogMH0KICAgIH0pCgphc3luYyBkZWYgaGFuZGxlX21vZGVscyhyZXF1ZXN0KToKICAgIHJldHVybiB3ZWIuanNvbl9yZXNwb25zZSh7ImRhdGEiOiBbeyJpZCI6IE1PREVMX0lELCAib2JqZWN0IjogIm1vZGVsIn1dLCAib2JqZWN0IjogImxpc3QifSkKCmFwcCA9IHdlYi5BcHBsaWNhdGlvbigpCmFwcC5yb3V0ZXIuYWRkX3Bvc3QoIi92MS9jaGF0L2NvbXBsZXRpb25zIiwgaGFuZGxlX2NoYXQpCmFwcC5yb3V0ZXIuYWRkX2dldCgiL3YxL21vZGVscyIsIGhhbmRsZV9tb2RlbHMpCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgbG9nKGYiU3RhcnRpbmcgb24gOjUwMDIiKQogICAgd2ViLnJ1bl9hcHAoYXBwLCBob3N0PSIwLjAuMC4wIiwgcG9ydD01MDAyLCBwcmludD1sYW1iZGEgeDogbG9nKHgpKQo=
VLM_B64EOF

echo "[4c/6] Writing video generator..."
base64 -d << 'VID_B64EOF' > "$HOME/generate_video.py"
IiIiVmlkZW8gZ2VuZXJhdGlvbiB1c2luZyBXYW4gMi4xIG9uIEFwcGxlIFNpbGljb24gKE1QUykKTWVtb3J5LWVmZmljaWVudDogbG9hZHMgbW9kZWwgb24gZGVtYW5kLCB1bmxvYWRzIGFmdGVyIGdlbmVyYXRpb24iIiIKaW1wb3J0IHRvcmNoLCBzeXMsIHRpbWUsIG9zLCBnYwoKZGVmIGdlbmVyYXRlKHByb21wdCwgb3V0cHV0X3BhdGg9Im91dHB1dC5tcDQiLCBudW1fZnJhbWVzPTE3LCBoZWlnaHQ9NDgwLCB3aWR0aD04MzIsIHN0ZXBzPTIwKToKICAgIGZyb20gZGlmZnVzZXJzIGltcG9ydCBXYW5QaXBlbGluZSwgQXV0b2VuY29kZXJLTFdhbgogICAgZnJvbSBkaWZmdXNlcnMudXRpbHMgaW1wb3J0IGV4cG9ydF90b192aWRlbwoKICAgIGRldmljZSA9ICJtcHMiIGlmIHRvcmNoLmJhY2tlbmRzLm1wcy5pc19hdmFpbGFibGUoKSBlbHNlICJjcHUiCiAgICBwcmludChmIkRldmljZToge2RldmljZX0iKQogICAgcHJpbnQoZiJQcm9tcHQ6IHtwcm9tcHR9IikKICAgIHByaW50KGYiRnJhbWVzOiB7bnVtX2ZyYW1lc30sIFNpemU6IHt3aWR0aH14e2hlaWdodH0sIFN0ZXBzOiB7c3RlcHN9IikKCiAgICBtb2RlbF9pZCA9ICJXYW4tQUkvV2FuMi4xLVQyVi0xLjNCLURpZmZ1c2VycyIKICAgIHByaW50KGYiTG9hZGluZyB7bW9kZWxfaWR9Li4uIikKCiAgICB2YWUgPSBBdXRvZW5jb2RlcktMV2FuLmZyb21fcHJldHJhaW5lZCgKICAgICAgICBtb2RlbF9pZCwgc3ViZm9sZGVyPSJ2YWUiLCB0b3JjaF9kdHlwZT10b3JjaC5mbG9hdDMyCiAgICApCiAgICBwaXBlID0gV2FuUGlwZWxpbmUuZnJvbV9wcmV0cmFpbmVkKAogICAgICAgIG1vZGVsX2lkLCB2YWU9dmFlLCB0b3JjaF9kdHlwZT10b3JjaC5mbG9hdDMyCiAgICApCiAgICBwaXBlLnRvKGRldmljZSkKICAgIHBpcGUuZW5hYmxlX2F0dGVudGlvbl9zbGljaW5nKCkKCiAgICBwcmludCgiR2VuZXJhdGluZy4uLiIpCiAgICB0MCA9IHRpbWUudGltZSgpCgogICAgb3V0cHV0ID0gcGlwZSgKICAgICAgICBwcm9tcHQ9cHJvbXB0LAogICAgICAgIG51bV9mcmFtZXM9bnVtX2ZyYW1lcywKICAgICAgICBoZWlnaHQ9aGVpZ2h0LAogICAgICAgIHdpZHRoPXdpZHRoLAogICAgICAgIG51bV9pbmZlcmVuY2Vfc3RlcHM9c3RlcHMsCiAgICAgICAgZ3VpZGFuY2Vfc2NhbGU9NS4wLAogICAgKS5mcmFtZXNbMF0KCiAgICBlbGFwc2VkID0gdGltZS50aW1lKCkgLSB0MAogICAgcHJpbnQoZiJHZW5lcmF0ZWQgaW4ge2VsYXBzZWQ6LjFmfXMgKHtlbGFwc2VkL251bV9mcmFtZXM6LjFmfXMvZnJhbWUpIikKCiAgICBvcy5tYWtlZGlycyhvcy5wYXRoLmRpcm5hbWUob3V0cHV0X3BhdGgpIGlmIG9zLnBhdGguZGlybmFtZShvdXRwdXRfcGF0aCkgZWxzZSAiLiIsIGV4aXN0X29rPVRydWUpCiAgICBleHBvcnRfdG9fdmlkZW8ob3V0cHV0LCBvdXRwdXRfcGF0aCwgZnBzPTgpCiAgICBwcmludChmIlNhdmVkOiB7b3V0cHV0X3BhdGh9IikKCiAgICAjIEZyZWUgbWVtb3J5CiAgICBkZWwgcGlwZSwgdmFlLCBvdXRwdXQKICAgIGdjLmNvbGxlY3QoKQogICAgaWYgZGV2aWNlID09ICJtcHMiOgogICAgICAgIHRvcmNoLm1wcy5lbXB0eV9jYWNoZSgpCiAgICBwcmludCgiTWVtb3J5IHJlbGVhc2VkIikKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBwcm9tcHQgPSBzeXMuYXJndlsxXSBpZiBsZW4oc3lzLmFyZ3YpID4gMSBlbHNlICJBIGNhdCB3YWxraW5nIG9uIGEgYmVhY2ggYXQgc3Vuc2V0IgogICAgb3V0cHV0ID0gc3lzLmFyZ3ZbMl0gaWYgbGVuKHN5cy5hcmd2KSA+IDIgZWxzZSBmImdlbmVyYXRlZC92aWRlb197aW50KHRpbWUudGltZSgpKX0ubXA0IgogICAgZ2VuZXJhdGUocHJvbXB0LCBvdXRwdXQpCg==
VID_B64EOF

# -------------------------------------------------------
# 5. ai.sh (start/stop/status/test)
# -------------------------------------------------------
echo "[5/6] Writing ~/ai.sh..."
cat > "$HOME/ai.sh" << 'SHEOF'
#!/bin/bash
# Multi-model MLX server manager — auto-detects RAM
PORT_MAIN=5000
PORT_FAST=5001
PROXY_PORT=4001
VENV=~/mlx_env/bin/activate
PROXY_BIN=~/proxy-rs/target/release/anthropic-proxy

# Auto-detect RAM tier
RAM_GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
if [ "$RAM_GB" -le 18 ]; then
  MODEL_MAIN="mlx-community/Qwen3.5-4B-4bit"; MODEL_FAST=""
elif [ "$RAM_GB" -le 24 ]; then
  MODEL_MAIN="mlx-community/Qwen3.5-9B-4bit"; MODEL_FAST=""
elif [ "$RAM_GB" -le 36 ]; then
  MODEL_MAIN="mlx-community/Qwen3.5-35B-A3B-4bit"; MODEL_FAST=""
elif [ "$RAM_GB" -le 64 ]; then
  MODEL_MAIN="mlx-community/Qwen3.5-35B-A3B-4bit"; MODEL_FAST="mlx-community/Qwen3.5-9B-4bit"
elif [ "$RAM_GB" -le 96 ]; then
  MODEL_MAIN="mlx-community/Qwen3.5-122B-A10B-4bit"; MODEL_FAST=""
else
  MODEL_MAIN="mlx-community/Qwen3.5-122B-A10B-4bit"; MODEL_FAST="mlx-community/Qwen3.5-35B-A3B-4bit"
fi
# Allow env override
MODEL_MAIN="${MLX_MODEL_MAIN:-$MODEL_MAIN}"
MODEL_FAST="${MLX_MODEL_FAST:-$MODEL_FAST}"

start_model() {
  local model=$1 port=$2 label=$3 logfile=$4
  if curl -s http://127.0.0.1:$port/v1/models 2>/dev/null | grep -q "model"; then
    echo "  $label: already running (:$port)"
    return 0
  fi
  echo "  $label starting (:$port)..."
  nohup mlx_lm.server --model "$model" --port $port > ~/$logfile 2>&1 &
  for i in $(seq 1 40); do
    curl -s http://127.0.0.1:$port/v1/models 2>/dev/null | grep -q "model" && break
    [ $i -eq 40 ] && { echo "  $label: TIMEOUT"; return 1; }
    sleep 3
  done
  echo "  $label: ready"
}

start() {
  if pgrep -f "anthropic_proxy" > /dev/null; then
    echo "Already running. ~/ai.sh status"
    return 1
  fi
  source "$VENV"

  echo "Starting MLX servers..."
  start_model "$MODEL_MAIN" $PORT_MAIN "main (122B)" "mlx_main.log"

  # Fast model is optional — start in background, don't block
  start_model "$MODEL_FAST" $PORT_FAST "fast (35B)" "mlx_fast.log" &

  echo "Proxy starting..."
  nohup python3 ~/anthropic_proxy.py > ~/proxy.log 2>&1 &
  sleep 2

  IP=$(ipconfig getifaddr en0 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')
  echo ""
  echo "========================================"
  echo " Ready!"
  echo " Sonnet/Opus -> $MODEL_MAIN (:$PORT_MAIN)"
  echo " Haiku       -> $MODEL_FAST (:$PORT_FAST)"
  echo " Proxy       -> http://$IP:$PROXY_PORT"
  echo "========================================"
  echo " cld  -> Claude Code (local)"
  echo " clc  -> Claude Code (Anthropic cloud)"
  echo "========================================"
}

stop() {
  pkill -f "mlx_lm.server" 2>/dev/null
  pkill -f "anthropic_proxy" 2>/dev/null
  echo "Stopped"
}

status() {
  echo "=== Models ==="
  curl -s http://127.0.0.1:$PORT_MAIN/v1/models 2>/dev/null | grep -q model \
    && echo "main (122B): running (:$PORT_MAIN)" || echo "main (122B): stopped"
  curl -s http://127.0.0.1:$PORT_FAST/v1/models 2>/dev/null | grep -q model \
    && echo "fast (35B):  running (:$PORT_FAST)" || echo "fast (35B):  stopped"
  echo "=== Proxy ==="
  pgrep -f "anthropic_proxy" > /dev/null \
    && echo "Proxy: running (:$PROXY_PORT)" || echo "Proxy: stopped"
}

test_it() {
  for m in claude-sonnet-4-6 claude-haiku-4-5-20251001; do
    R=$(curl -s http://127.0.0.1:$PROXY_PORT/v1/messages \
      -H "Content-Type: application/json" \
      -H "x-api-key: dummy" \
      -H "anthropic-version: 2023-06-01" \
      -d "{\"model\":\"$m\",\"messages\":[{\"role\":\"user\",\"content\":\"1+1=?\"}],\"max_tokens\":20}")
    C=$(echo "$R" | python3 -c 'import sys,json;print(json.load(sys.stdin)["content"][0]["text"])' 2>/dev/null)
    [ -n "$C" ] && echo "$m -> OK: $C" || echo "$m -> Error"
  done
}

case "${1:-start}" in
  start) start ;; stop) stop ;; status) status ;; test) test_it ;; restart) stop; sleep 2; start ;;
  *) echo "~/ai.sh [start|stop|status|test|restart]" ;;
esac
SHEOF
chmod +x "$HOME/ai.sh"

# -------------------------------------------------------
# 6. Shell aliases + Claude Code settings
# -------------------------------------------------------
echo "[6/6] Configuring shell & Claude Code..."

cat > "$HOME/ai-switch.py" << 'SWEOF'
#!/usr/bin/env python3
import json, sys, os
SETTINGS = os.path.expanduser("~/.claude/settings.json")
def switch(mode):
    try:
        with open(SETTINGS) as f: d = json.load(f)
    except: d = {}
    if mode == "local":
        d["env"] = {"ANTHROPIC_BASE_URL": "http://127.0.0.1:4001", "ANTHROPIC_API_KEY": "sk-ant-dummy"}
        print("-> Local Qwen3.5 (MLX)")
    elif mode == "cloud":
        d.pop("env", None)
        print("-> Anthropic Cloud")
    else:
        print("Usage: ai-switch.py [local|cloud]"); return
    os.makedirs(os.path.dirname(SETTINGS), exist_ok=True)
    with open(SETTINGS, "w") as f: json.dump(d, f, indent=2)
if __name__ == "__main__":
    switch(sys.argv[1] if len(sys.argv) > 1 else "")
SWEOF
chmod +x "$HOME/ai-switch.py"

MARKER="# === Local Claude Code ==="
if ! grep -q "$MARKER" "$HOME/.zshrc" 2>/dev/null; then
  cat >> "$HOME/.zshrc" << 'RCEOF'

# === Local Claude Code ===
export PATH="/opt/homebrew/bin:$PATH"
ai-local() { python3 ~/ai-switch.py local; export ANTHROPIC_BASE_URL=http://127.0.0.1:4001; export ANTHROPIC_API_KEY=sk-ant-dummy; }
ai-cloud() { python3 ~/ai-switch.py cloud; unset ANTHROPIC_BASE_URL; unset ANTHROPIC_API_KEY; }
alias cld='ai-local && claude --dangerously-skip-permissions'
alias clc='ai-cloud && claude'
RCEOF
  echo "  Added aliases to ~/.zshrc"
else
  echo "  ~/.zshrc already configured"
fi

mkdir -p "$HOME/.claude"
python3 "$HOME/ai-switch.py" local

echo ""
echo "========================================"
echo " Setup complete!"
echo "========================================"
echo ""
echo " 1. ~/ai.sh start   -> Start MLX + proxy"
echo " 2. cld              -> Claude Code (local, tool_use OK)"
echo "    clc              -> Claude Code (Anthropic cloud)"
echo " 3. ~/ai.sh stop     -> Stop everything"
echo ""
echo " First run: ~/ai.sh start"
echo "========================================"
